<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 *************************************************************************************/
$languageStrings = array(
	'LayoutEditor'                  => 'Editor de Layout',
	'LBL_FIELDS_AND_LAYOUT_EDITOR'  => 'Editor de Campos e Layout',
	'LBL_CREATE_CUSTOM_FIELD'       => 'Criar Campo Personalizado',
	'LBL_DETAILVIEW_LAYOUT'         => 'Layout da Visão de Detalhe',
	'LBL_ARRANGE_RELATED_TABS'      => 'Organizar Abas Relacionadas',
	'LBL_ADD_CUSTOM_FIELD'          => 'Adicionar Campo Personalizado',
	'LBL_ADD_CUSTOM_BLOCK'          => 'Adicionar Bloco Personalizado',
	'ADD_CUSTOM_FIELD'              => 'Adicionar Campo Personalizado',
	'ADD_CUSTOM_BLOCK'              => 'Adicionar Bloco Personalizado',
	'LBL_SAVE_FIELD_SEQUENCE'       => 'Salvar Sequência de Campos',
	'LBL_BLOCK_NAME'                => 'Nome do Bloco',
	'LBL_ADD_AFTER'                 => 'Adicionar Após',
	'LBL_ACTIONS'                   => 'Ações',
	'LBL_ALWAYS_SHOW'               => 'Sempre Exibir',
	'LBL_SHOW_INACTIVE_FIELDS'      => 'Exibir Campos Inativos',
	'LBL_SHOW_HIDDEN_FIELDS'        => 'Mostrar Campos Ocultos',
	'LBL_DELETE_CUSTOM_BLOCK'       => 'Excluir Bloco Personalizado',
	'LBL_MANDATORY_FIELD'           => 'Campo Obrigatório',
	'LBL_ACTIVE'                    => 'Ativo',
	'LBL_QUICK_CREATE'              => 'Criação Rápida',
	'LBL_SUMMARY_FIELD'             => 'Visão de Resumo',
	'LBL_KEY_FIELD_VIEW'            => 'Visão de Campo Chave',
	'LBL_MASS_EDIT'                 => 'Edição em Massa',
	'LBL_DEFAULT_VALUE'             => 'Valor Padrão',
	'LBL_SELECT_FIELD_TYPE'         => 'Selecionar Tipo de Campo',
	'LBL_LABEL_NAME'                => 'Nome do Rótulo',
	'LBL_LENGTH'                    => 'Comprimento',
	'LBL_DECIMALS'                  => 'Casas Decimais',
	'LBL_ENTER_PICKLIST_VALUES'     => 'Inserir Valores da Lista..',
	'LBL_PICKLIST_VALUES'           => 'Valores da Lista',
	'LBL_INACTIVE_FIELDS'           => 'Campos Inativos',
	'LBL_REACTIVATE'                => 'Reativar',
	'LBL_ARRANGE_RELATED_LIST'      => 'Organizar Lista Relacionada',
	'LBL_SELECT_MODULE_TO_ADD'      => 'Selecionar Módulo para Adicionar',
	'LBL_SELECT_HIDDEN_MODULE'      => 'Selecionar módulo oculto',
	'LBL_NO_RELATED_INFORMATION'    => 'Sem Informação Relacionada',
	'LBL_RELATED_LIST_INFO'         => 'Arraste e solte o módulo para reordenar a lista',
	'LBL_REMOVE_INFO'               => 'Clique no ícone de exclusão para remover o relacionamento da lista',
	'LBL_ADD_MODULE_INFO'           => 'Selecione o módulo removido para readicioná-lo à lista',
	'LBL_MANY_MANY_TEXT'            => 'Relacionamentos Muitos-para-Muitos disponíveis apenas para %s e %s',
	'LBL_SELECT_MODULE'             => 'Selecionar Módulo..',
	'LBL_DUPLICATES_EXIST'          => 'Nome do Bloco já existe',
	'LBL_NON_ROLE_BASED_PICKLIST'   => 'Lista Não Baseada em Perfil',
	'LBL_DUPLICATE_FIELD_EXISTS'    => 'Campo Duplicado Existe',
	'LBL_WRONG_FIELD_TYPE'          => 'Tipo de Campo Incorreto',
	'LBL_ROLE_BASED_PICKLIST'       => 'Lista Baseada em Perfil',
	'LBL_CLICK_HERE_TO_EDIT'        => 'Clique aqui para editar',
	'LBL_EDIT_FIELD'                => 'Editar propriedades do campo: %s',

	// Tipos de Campo
	'Text'                          => 'Texto',
	'Decimal'                       => 'Decimal',
	'Integer'                       => 'Inteiro',
	'Percent'                       => 'Percentual',
	'Currency'                      => 'Moeda',
	'Date'                          => 'Data',
	'Email'                         => 'E-mail',
	'Phone'                         => 'Telefone',
	'PickList'                      => 'Lista de Seleção',
	'MultiSelectCombo'              => 'Caixa de Seleção Múltipla',
	'URL'                           => 'URL',
	'Checkbox'                      => 'Caixa de Seleção',
	'TextArea'                      => 'Área de Texto',
	'Skype'                         => 'Skype',
	'Time'                          => 'Hora',
	'Calendar'                      => 'Tarefa',
	'LBL_FIELD_COULD_NOT_BE_CREATED'=> 'Campo %s não pôde ser criado',
	'SELECT_MODULE'                 => 'Selecionar Módulo',

	// Listas Relacionadas
	'LBL_RELATION_SHIPS'            => 'Relacionamentos',
	'LBL_ADD_RELATIONSHIP'          => 'Adicionar Relacionamento',
	'LBL_RELATED_MODULE'            => 'Módulo Relacionado',
	'LBL_ADDING_RELATIONSHIP'       => 'Adicionando Relacionamento para %s',
	'LBL_SELECTED_RELATED_MODULE'   => 'Selecionar módulo relacionado',
	'LBL_SELECTED_RELATION_TYPE'    => 'Selecionar tipo de relacionamento',
	'ONE_ONE_AND_MANY_ONE_RELATIONSHIP' => 'Relacionamentos Um-para-Um e Muitos-para-Um',
	'ONE_MANY_RELATIONSHIP'         => 'Relacionamentos Um-para-Muitos e Muitos-para-Muitos',
	'1-1'                           => 'Um para Um',
	'1-N'                           => 'Um para Muitos',
	'N-1'                           => 'Muitos para Um',
	'N-N'                           => 'Muitos para Muitos',

	// Novo layout
	'LBL_FIELD_TYPES'               => 'Tipos de Campo',
	'LBL_BASIC_FIELDS'              => 'Campos Básicos',
	'LBL_MANDATORY'                 => 'Campo Obrigatório',
	'LBL_PROPERTIES'                => 'Propriedades',
	'LBL_DRAG_UI_TYPE'              => 'Arraste e Solte o Campo aqui',
	'LBL_RELATION_FIELDS'           => 'Campos de Relacionamento',
	'LBL_SELECT_BLOCK'              => 'Selecionar Bloco',
	'LBL_RELATION_ADDED_SUCCESS'    => 'Relacionamento adicionado com sucesso',
	'FIELD_NAME_IN_PRIMARY_MODULE'  => 'Campo de relação em %s',
	'FIELD_NAME_IN_RELATED_MODULE'  => 'Campo de relação em %s',
	'TAB_IN_PRIMARY_MODULE'         => 'Tabela/Aba em %s',
	'TAB_IN_RELATED_MODULE'         => 'Tabela/Aba em %s',
	'LBL_DETAIL_VIEW'               => 'Visão de Detalhe',
	'LBL_EXPANDED'                  => 'Expandido',
	'LBL_COLLAPSED'                 => 'Recolhido',
	'LBL_NO_RELATION_TYPE'          => 'Nenhum relacionamento deste tipo existe',
	'LBL_CREATE_ITEM_CUSTOM_FIELD'  => 'Criar Campo Personalizado de Item de Linha',
	'LBL_MAP_PRODUCT_FIELD'         => 'Mapear para campo de Produtos',
	'LBL_MAP_SERVICE_FIELD'         => 'Mapear para campo de Serviços',
	'LBL_ENABLE_TO_MAP_PRODUCT_FIELD'=> 'Habilitar para mapear campo de Produtos',
	'LBL_ENABLE_TO_MAP_SERVICE_FIELD'=> 'Habilitar para mapear campo de Serviços',

	// Vtiger 7
	'LBL_NO_RELATED_INFO'           => 'Nenhum Relacionamento existe',
	'LBL_ADD_NEW_FIELD_HERE'        => 'Adicionar novo campo aqui',
	'LBL_SAVE_LAYOUT'               => 'Salvar Layout',
	'LBL_SHOW_FIELD'                => 'Exibir Campo',
	'LBL_ENABLE_OR_DISABLE_FIELD_PROP' => 'Habilitar / Desabilitar propriedades do campo',
	'LBL_PROP_MANDATORY'            => 'Obrigatório',
	'LBL_DEFAULT_VALUE_NOT_SET'     => 'Valor padrão não definido',
	'LBL_INFO'                      => 'Informação',
	'LBL_PRODUCTFIELDDEFAULTVALUE'  => ' (Produtos)',
	'LBL_SERVICEFIELDDEFAULTVALUE'  => ' (Serviços)',
	'LBL_SHOW_THIS_FIELD_IN'        => 'Clique aqui para exibir este campo na visão %s',
	'LBL_MAKE_THIS_FIELD'           => 'Clique aqui para tornar este campo %s',
	'LBL_HIDE_THIS_FIELD_IN'        => 'Clique aqui para ocultar este campo na visão %s',
	'LBL_NOT_MAKE_THIS_FIELD'       => 'Clique aqui para tornar este campo não-%s',
	'LBL_COLLAPSE_BLOCK'            => 'Recolher Bloco',
	'LBL_COLLAPSE_BLOCK_DETAIL_VIEW'=> 'Recolher o bloco na visão de detalhe',
	'LBL_HEADER'                    => 'Cabeçalho',
	'LBL_DETAIL_HEADER'             => 'Cabeçalho do Registro',
	'LBL_HEADER_FIELD'              => 'Visão de Cabeçalho',

	// Tratamento de Duplicatas
	'LBL_DUPLICATE_HANDLING'        => 'Tratamento de Duplicidades',
	'LBL_DUPLICATE_CHECK'           => 'Habilitar verificação de duplicatas',
	'LBL_DUPLICATION_INFO_MESSAGE'   => 'A prevenção de duplicatas só evita a criação de novos registros duplicados por usuários e aplicações externas. Registros criados via Importação e Workflows não são verificados.<br><br>Registros duplicados existentes podem ser removidos usando a função "Localizar Duplicatas" na página do módulo.',
	'LBL_DUPLICATES_IN_SYNC_MESSAGE' => 'Ação a tomar se um registro duplicado for encontrado durante a sincronização com aplicação externa',
	'LBL_SELECT_FIELDS_FOR_DUPLICATION' => 'Selecione os campos únicos para verificação de duplicatas',
	'LBL_SELECT_FIELDS'             => 'Selecionar Campos',
	'LBL_MAX_3_FIELDS'              => 'Máximo 3 Campos',
	'LBL_SELECT_RULE'               => 'Selecionar regra para tratamento de duplicatas',
	'LBL_ALLOW_DUPLICATES'          => 'Permitir Duplicatas',
	'LBL_DO_NOT_ALLOW_DUPLICATES'   => 'Não Permitir Duplicatas',
	'LBL_PREFER_LATEST_RECORD'      => 'Preferir registro mais recente',
	'LBL_PREFER_INTERNAL_RECORD'    => 'Preferir registro interno',
	'LBL_PREFER_EXTERNAL_RECORD'    => 'Preferir registro externo',

	// Sidebar (contexto Settings)
	'LBL_MODULE_CUSTOMIZATION'      => 'Layouts e Campos de Módulos',
	'LBL_PICKLIST_DEPENDENCY'       => 'Dependência de Listas',
	'LBL_EXTENSION_STORE'           => 'Loja de Extensões',
	'LBL_GOOGLE'                    => 'Google',
);

$jsLanguageStrings = array(
	'JS_BLOCK_VISIBILITY_SHOW'      => 'Exibição de bloco habilitada',
	'JS_BLOCK_VISIBILITY_HIDE'      => 'Ocultação de bloco habilitada',
	'JS_CUSTOM_BLOCK_ADDED'         => 'Novo Bloco Personalizado adicionado',
	'JS_BLOCK_SEQUENCE_UPDATED'     => 'Sequência de Blocos Atualizada',
	'JS_SELECTED_FIELDS_REACTIVATED'=> 'Campos Selecionados Reativados',
	'JS_FIELD_DETAILS_SAVED'        => 'Detalhes do Campo Salvos',
	'JS_CUSTOM_BLOCK_DELETED'       => 'Bloco Personalizado Excluído',
	'JS_CUSTOM_FIELD_ADDED'         => 'Campo %s Adicionado',
	'JS_CUSTOM_FIELD_DELETED'       => 'Campo Personalizado Excluído',
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => 'O comprimento deve ser menor ou igual a',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5'   => 'Decimal deve estar no intervalo de 2 a 5',
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => 'Salve as alterações para atualizar a sequência de campos',
	'JS_RELATED_INFO_SAVED'         => 'Informação Relacionada Salva',
	'JS_BLOCK_NAME_EXISTS'          => 'Nome do Bloco já existe',
	'JS_NO_HIDDEN_FIELDS_EXISTS'    => 'Sem Campos Inativos',
	'JS_SPECIAL_CHARACTERS'         => 'Caracteres especiais como',
	'JS_NOT_ALLOWED'                => 'não são permitidos',
	'JS_FIELD_SEQUENCE_UPDATED'     => 'Sequência de Campos Atualizada',
	'JS_DUPLICATES_VALUES_FOUND'    => 'Valores Duplicados encontrados',
	'JS_PROP_MANDATORY'             => 'Obrigatório',
	'JS_SUMMARY'                    => 'Resumo',
	'JS_KEY_FIELD'                  => 'Campo Chave',
	'JS_QUICK_CREATE'               => 'Criação Rápida',
	'JS_MASS_EDIT'                  => 'Edição em Massa',
	'JS_DEFAULT_VALUE_NOT_SET'      => 'Valor padrão não definido',
	'JS_DEFAULT_VALUE'              => 'Valor Padrão',
	'JS_SAVE_MODULE_SEQUENCE'       => 'Salve as alterações para atualizar a sequência de módulos',
	'JS_DETAIL_HEADER'              => 'Cabeçalho do Registro',
	'JS_MAXIMUM_HEADER_FIELDS_ALLOWED' => 'Máximo de %s campos de cabeçalho permitidos',
	'JS_NAME_FIELDS_APPEAR_IN_HEADER_BY_DEFAULT' => 'Campos de nome aparecem no cabeçalho por padrão',
	'JS_DUPLICATE_HANDLING_SUCCESS_MESSAGE' => 'Campos selecionados atualizados para prevenção de duplicatas',
	'JS_DUPLICATE_HANDLING_FAILURE_MESSAGE' => 'Falha ao atualizar campos para prevenção de duplicatas',
	'JS_DUPLICATE_CHECK_DISABLED'   => 'Verificação de duplicatas desabilitada',
	'JS_STATUS_CHANGED_SUCCESSFULLY'=> 'Status alterado com sucesso',
);
